apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>My Page:Abhishek</title>
    </head>
    <body>
        <h1>Welcome to my page</h1>
    </body>
    </html>
